# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20170422_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseType', models.CharField(default='자취방', max_length=255)),
                ('houseName', models.CharField(default='찬주의 자취방', max_length=255)),
                ('houseIntro', models.CharField(default='고양이가 있는 짠주의 자취방이에욥', max_length=255)),
                ('HouseLocation', models.CharField(default='서울시 성북구 안암동 1, 고려대학교 파이빌 91호', max_length=255)),
                ('adminUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
