# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='HouseLocation',
            new_name='houseLocation',
        ),
    ]
