# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170422_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='deviceWifiAddr',
            field=models.CharField(default='127.0.0.0', max_length=255),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='full_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='locale',
            field=models.CharField(default='', max_length=10),
        ),
    ]
