# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170427_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='aeName',
            field=models.CharField(choices=[('ae-secondled', 'ae-secondled'), ('ae-jyp', 'ae-jyp')], default=('ae-secondled', 'ae-secondled'), max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='cntName',
            field=models.CharField(choices=[('cnt-led', 'cnt-led'), ('cnt-ultra', 'cnt-ultra')], default=('cnt-led', 'cnt-led'), max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='content',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='roomName',
            field=models.CharField(default='거실', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='subscribeOnOffState',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceCom',
            field=models.CharField(choices=[('smArts', 'smArts')], default=('smArts', 'smArts'), max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceName',
            field=models.CharField(choices=[('led', 'LED전등'), ('ultra', '초음파감지기')], default=('led', 'LED전등'), max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceType',
            field=models.CharField(choices=[('bulb', '전등'), ('sensor', '센서')], default=('bulb', '전등'), max_length=255),
        ),
    ]
