# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170808_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='aeName',
            field=models.CharField(choices=[('ae-secondled', 'ae-secondled'), ('ae-jyp', 'ae-jyp')], default='ae-secondled', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='cntName',
            field=models.CharField(choices=[('cnt-led', 'cnt-led'), ('cnt-ultra', 'cnt-ultra')], default='cnt-led', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceCom',
            field=models.CharField(choices=[('smArts', 'smArts')], default='smArts', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceName',
            field=models.CharField(choices=[('led', 'LED전등'), ('ultra', '초음파감지기')], default='led', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceType',
            field=models.CharField(choices=[('bulb', '전등'), ('sensor', '센서')], default='bulb', max_length=255),
        ),
    ]
