# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170808_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='deviceWifiAddr',
        ),
    ]
