# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_device_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='aeName',
            field=models.CharField(choices=[('ae-secondled', 'ae-secondled'), ('ae-jyp', 'ae-jyp'), ('ae-humidity', 'ae-humidity')], default='ae-secondled', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='cntName',
            field=models.CharField(choices=[('cnt-led', 'cnt-led'), ('cnt-ultra', 'cnt-ultra'), ('cnt-dht', 'cnt-dht')], default='cnt-led', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceName',
            field=models.CharField(choices=[('led', 'LED전등'), ('ultra', '초음파감지기'), ('humidity', '온습도측정')], default='led', max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceType',
            field=models.CharField(choices=[('bulb', '전등'), ('ultrasensor', '초음파센서'), ('humiditysensor', '온습도센서')], default='bulb', max_length=255),
        ),
    ]
