# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170810_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='aeName',
            field=models.CharField(choices=[('ae-smarts', 'ae-secondled'), ('ae-smarts', 'ae-jyp'), ('ae-smarts', 'ae-humidity')], default='ae-smarts', max_length=255),
        ),
    ]
