# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170812_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceCom',
            field=models.CharField(choices=[('smArts', 'smArts'), ('smArts', 'smArts'), ('smArts', 'smArts'), ('Philips', 'Philips')], default='smArts', max_length=255),
        ),
    ]
